Resources:
  kitamuraAppUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.profile}-users-${self:provider.stage}
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: line_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: line_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1 